import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderSuspense, ssrRenderComponent, ssrRenderStyle } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"FFI topology","description":"FocalPoint documentation","frontmatter":{"title":"FFI topology","description":"FocalPoint documentation"},"headers":[],"relativePath":"architecture/ffi-topology.md","filePath":"architecture/ffi-topology.md","lastUpdated":1776935227000}');
const _sfc_main = { name: "architecture/ffi-topology.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Mermaid = resolveComponent("Mermaid");
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="ffi-topology" tabindex="-1">FFI topology <a class="header-anchor" href="#ffi-topology" aria-label="Permalink to &quot;FFI topology&quot;">​</a></h1><p>How the Rust core is exposed to Swift (today) and Kotlin (Phase 2+).</p><h2 id="uniffi-rust-→-swift" tabindex="-1">UniFFI: Rust → Swift <a class="header-anchor" href="#uniffi-rust-→-swift" aria-label="Permalink to &quot;UniFFI: Rust → Swift&quot;">​</a></h2><p>The core&#39;s public API is defined in <code>crates/focus-ffi/src/lib.rs</code> with <code>#[uniffi::export]</code>. <code>uniffi-bindgen</code> generates:</p><ul><li>A <code>.swift</code> module wrapping the C ABI.</li><li>A <code>.h</code> header.</li><li>An <code>XCFramework</code>-compatible static library (<code>libfocus_ffi.a</code> per target).</li></ul>`);
  ssrRenderSuspense(_push, {
    default: () => {
      _push(ssrRenderComponent(_component_Mermaid, {
        id: "mermaid-29",
        class: "mermaid",
        graph: "flowchart%20LR%0A%20%20subgraph%20rust%5B%22Rust%20workspace%22%5D%0A%20%20%20%20focus_ffi%5B%22focus-ffi%3Cbr%2F%3E%23%5Buniffi%3A%3Aexport%5D%22%5D%0A%20%20%20%20focus_domain%5B%22focus-domain%20%2B%20traits%22%5D%0A%20%20end%0A%0A%20%20subgraph%20tooling%5B%22Build%20tooling%22%5D%0A%20%20%20%20cargo%5B%22cargo%20build%20--release%3Cbr%2F%3E--target%20aarch64-apple-ios%3Cbr%2F%3E--target%20aarch64-apple-ios-sim%3Cbr%2F%3E--target%20x86_64-apple-ios%22%5D%0A%20%20%20%20uniffi%5B%22uniffi-bindgen%20generate%22%5D%0A%20%20%20%20xcframework%5B%22xcodebuild%20-create-xcframework%22%5D%0A%20%20end%0A%0A%20%20subgraph%20ios%5B%22iOS%20app%22%5D%0A%20%20%20%20swiftpkg%5B%22FocalPointCore.xcframework%22%5D%0A%20%20%20%20swiftui%5B%22SwiftUI%20views%22%5D%0A%20%20%20%20adapter%5B%22Swift%20adapters%3Cbr%2F%3E(FamilyControls%2C%20Keychain%2C%20Spline)%22%5D%0A%20%20end%0A%0A%20%20focus_ffi%20--%3E%20cargo%0A%20%20focus_domain%20--%3E%20focus_ffi%0A%20%20cargo%20--%3E%20uniffi%0A%20%20uniffi%20--%3E%20xcframework%0A%20%20xcframework%20--%3E%20swiftpkg%0A%20%20swiftpkg%20--%3E%20swiftui%0A%20%20swiftpkg%20--%3E%20adapter%0A"
      }, null, _parent));
    },
    fallback: () => {
      _push(` Loading... `);
    },
    _: 1
  });
  _push(`<h2 id="boundary-rules" tabindex="-1">Boundary rules <a class="header-anchor" href="#boundary-rules" aria-label="Permalink to &quot;Boundary rules&quot;">​</a></h2><ol><li><strong>Owned types only cross the boundary.</strong> No references held across FFI calls; the core hands out opaque handles.</li><li><strong>No panics escape.</strong> All <code>#[uniffi::export]</code> methods return <code>Result&lt;T, CoreError&gt;</code>; unwinds are caught at the boundary.</li><li><strong>No blocking on the main thread.</strong> Swift wraps long-running calls (<code>verify_chain_from_genesis</code>, <code>connector_sync</code>) in <code>Task.detached</code>.</li><li><strong>No domain types in Swift.</strong> Swift declares nothing of its own for rules, events, or audit records — it consumes <code>uniffi</code>-generated Swift enums and structs.</li><li><strong>No callbacks without explicit registration.</strong> The core publishes events via a registered <code>CoreObserver</code> trait object that Swift implements.</li></ol><h2 id="error-mapping" tabindex="-1">Error mapping <a class="header-anchor" href="#error-mapping" aria-label="Permalink to &quot;Error mapping&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Rust: CoreError enum (thiserror)</span></span>
<span class="line"><span>  AuthExpired { connector: String }</span></span>
<span class="line"><span>  RateLimited { retry_after_ms: u64 }</span></span>
<span class="line"><span>  ChainBroken { at_index: u64 }</span></span>
<span class="line"><span>  ...</span></span>
<span class="line"><span>  ↓</span></span>
<span class="line"><span>UniFFI: Swift enum CoreError: LocalizedError</span></span>
<span class="line"><span>  .authExpired(connector: String)</span></span>
<span class="line"><span>  .rateLimited(retryAfter: TimeInterval)</span></span>
<span class="line"><span>  .chainBroken(atIndex: UInt64)</span></span>
<span class="line"><span>  ...</span></span></code></pre></div><p>Every variant has a <code>LocalizedError</code> description string authored in Rust and surfaced verbatim in the iOS UI — one source of truth for error copy.</p><h2 id="android-phase-2" tabindex="-1">Android (Phase 2+) <a class="header-anchor" href="#android-phase-2" aria-label="Permalink to &quot;Android (Phase 2+)&quot;">​</a></h2><p>The same <code>focus-ffi</code> crate will generate Kotlin via <code>uniffi-kotlin</code>. Expected topology:</p><ul><li>Shared <code>.so</code> per Android ABI (arm64-v8a, armeabi-v7a, x86, x86_64).</li><li>Gradle plugin packages the <code>.so</code> into an <code>.aar</code>.</li><li>Kotlin bindings consumed by <code>apps/android/</code>.</li></ul><p>The trait surface is identical; only the adapter layer changes (UsageStats + Accessibility instead of FamilyControls).</p><h2 id="build-commands" tabindex="-1">Build commands <a class="header-anchor" href="#build-commands" aria-label="Permalink to &quot;Build commands&quot;">​</a></h2><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># iOS (via Taskfile)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">task</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build-ios-sim</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">task</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build-ios-device</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Under the hood:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --release</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -p</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> focus-ffi</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> \\</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  --target</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> aarch64-apple-ios</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> \\</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  --target</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> aarch64-apple-ios-sim</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> \\</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  --target</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> x86_64-apple-ios</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">uniffi-bindgen</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> generate</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --library</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> target/aarch64-apple-ios/release/libfocus_ffi.a</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> \\</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  --language</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> swift</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --out-dir</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> apps/ios/Generated</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">xcodebuild</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -create-xcframework</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> \\</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  -library</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> target/aarch64-apple-ios/release/libfocus_ffi.a</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> \\</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  -library</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> target/aarch64-apple-ios-sim/release/libfocus_ffi.a</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> \\</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  -library</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> target/x86_64-apple-ios/release/libfocus_ffi.a</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> \\</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  -output</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> apps/ios/FocalPointCore.xcframework</span></span></code></pre></div><p>This is scripted in <code>scripts/build-xcframework.sh</code> (to be added in Phase 1).</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("architecture/ffi-topology.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const ffiTopology = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  ffiTopology as default
};
