import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Architecture Decision Records","description":"FocalPoint documentation","frontmatter":{"title":"Architecture Decision Records","description":"FocalPoint documentation"},"headers":[],"relativePath":"architecture/adrs.md","filePath":"architecture/adrs.md","lastUpdated":1776935227000}');
const _sfc_main = { name: "architecture/adrs.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="architecture-decision-records" tabindex="-1">Architecture Decision Records <a class="header-anchor" href="#architecture-decision-records" aria-label="Permalink to &quot;Architecture Decision Records&quot;">​</a></h1><p>Accepted ADRs live in <a href="https://github.com/KooshaPari/FocalPoint/blob/main/ADR.md" target="_blank" rel="noreferrer"><code>ADR.md</code></a> at the repo root.</p><h2 id="index" tabindex="-1">Index <a class="header-anchor" href="#index" aria-label="Permalink to &quot;Index&quot;">​</a></h2><table tabindex="0"><thead><tr><th>ID</th><th>Title</th><th>Status</th></tr></thead><tbody><tr><td>ADR-001</td><td>Native iOS + Rust core; no cross-platform UI bridge</td><td>Accepted</td></tr><tr><td>ADR-002</td><td>Connector trait as public contract</td><td>Accepted</td></tr><tr><td>ADR-003</td><td>SQLite as local source of truth</td><td>Accepted</td></tr><tr><td>ADR-004</td><td>SHA-256 hash-chained audit log</td><td>Accepted</td></tr><tr><td>ADR-005</td><td>Dual ledger (rewards + penalties) over single scoring system</td><td>Accepted</td></tr><tr><td>ADR-006</td><td>Rule DSL in TOML, not Lua / JavaScript</td><td>Accepted</td></tr><tr><td>ADR-007</td><td>UniFFI over hand-written bindgen</td><td>Accepted</td></tr><tr><td>ADR-008</td><td>Fail-loudly error policy (no silent fallbacks)</td><td>Accepted</td></tr></tbody></table><p>The full text of each ADR lives in <a href="https://github.com/KooshaPari/FocalPoint/blob/main/ADR.md" target="_blank" rel="noreferrer"><code>ADR.md</code></a> and in the source-of-truth directory <code>docs/adr/</code> (as it&#39;s scaffolded in Phase 1).</p><h2 id="proposing-an-adr" tabindex="-1">Proposing an ADR <a class="header-anchor" href="#proposing-an-adr" aria-label="Permalink to &quot;Proposing an ADR&quot;">​</a></h2><ol><li>Copy the template from <code>docs/adr/0000-template.md</code> (to be added).</li><li>Number it sequentially.</li><li>Open a PR titled <code>adr: &lt;short title&gt;</code>.</li><li>Request review from the maintainer. ADRs require explicit acceptance; <code>rejected</code> and <code>superseded</code> are also valid terminal states.</li><li>Once accepted, add the row to this index and to <code>ADR.md</code>.</li></ol><h2 id="status-definitions" tabindex="-1">Status definitions <a class="header-anchor" href="#status-definitions" aria-label="Permalink to &quot;Status definitions&quot;">​</a></h2><ul><li><strong>Proposed</strong> — PR open, discussion ongoing.</li><li><strong>Accepted</strong> — merged, binding.</li><li><strong>Deprecated</strong> — still in effect, but a newer ADR supersedes part of it; migration ongoing.</li><li><strong>Superseded by ADR-XXX</strong> — no longer authoritative; cross-link to replacement.</li><li><strong>Rejected</strong> — closed without merging; kept in history for the reasoning.</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("architecture/adrs.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const adrs = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  adrs as default
};
