import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Apple Health Connector (Aspirational)","description":"Integrate sleep, activity, and mindfulness data into wellness-focused rules.","frontmatter":{"title":"Apple Health Connector (Aspirational)","description":"Integrate sleep, activity, and mindfulness data into wellness-focused rules."},"headers":[],"relativePath":"connectors/apple-health.md","filePath":"connectors/apple-health.md","lastUpdated":1777002546000}');
const _sfc_main = { name: "connectors/apple-health.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="apple-health-connector" tabindex="-1">Apple Health Connector <a class="header-anchor" href="#apple-health-connector" aria-label="Permalink to &quot;Apple Health Connector&quot;">​</a></h1><p><em>This connector is aspirational. Status: Planned for Q2 2026.</em></p><p>The Apple Health connector brings your sleep data, activity rings, and mindfulness sessions into FocalPoint, enabling wellness-focused rules and coaching.</p><h2 id="planned-features" tabindex="-1">Planned Features <a class="header-anchor" href="#planned-features" aria-label="Permalink to &quot;Planned Features&quot;">​</a></h2><ul><li><strong>Sleep tracking</strong>: Detect sleep debt and trigger evening lockdowns</li><li><strong>Activity rings</strong>: Reward focus sessions with activity goals</li><li><strong>Mindfulness minutes</strong>: Track meditation and breathing sessions</li><li><strong>Workouts</strong>: Sync exercise sessions to rule conditions</li></ul><h2 id="example-rule" tabindex="-1">Example Rule <a class="header-anchor" href="#example-rule" aria-label="Permalink to &quot;Example Rule&quot;">​</a></h2><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Sleep debt recovery&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">trigger</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  event_type</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;health.sleep_debt.high&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  threshold_hours</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">5</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">show_lockdown</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;evening_focus&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">coach_message</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Your sleep debt is {{hours}}h. Let&#39;s wind down early tonight.&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">schedule_ritual</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;morning_brief&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    at</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;next_morning&quot;</span></span></code></pre></div><h2 id="requires" tabindex="-1">Requires <a class="header-anchor" href="#requires" aria-label="Permalink to &quot;Requires&quot;">​</a></h2><ul><li><strong>HealthKit framework</strong> (iOS only)</li><li>User authorization to read sleep, activity, mindfulness data</li><li>iOS 17+</li></ul><h2 id="architecture-notes" tabindex="-1">Architecture Notes <a class="header-anchor" href="#architecture-notes" aria-label="Permalink to &quot;Architecture Notes&quot;">​</a></h2><p>Apple Health data is sensitive. The connector will:</p><ol><li>Request only the minimum required permissions (sleep, activity, mindfulness)</li><li>Process all data locally; never send to cloud</li><li>Store a local cache (SQLite) for rule evaluation</li><li>Allow users to audit what&#39;s being read via Settings → Privacy → HealthKit</li></ol><h2 id="implementation-status" tabindex="-1">Implementation Status <a class="header-anchor" href="#implementation-status" aria-label="Permalink to &quot;Implementation Status&quot;">​</a></h2><ul><li>[ ] HealthKit permission request</li><li>[ ] Sleep data sync</li><li>[ ] Activity ring integration</li><li>[ ] Local caching strategy</li><li>[ ] Privacy audit</li><li>[ ] iOS testing</li></ul><p>See <a href="./../architecture/ffi-topology">Architecture: FFI Topology</a> for how platform-specific permissions are bridged.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("connectors/apple-health.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const appleHealth = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  appleHealth as default
};
