import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"YNAB Connector (Aspirational)","description":"Integrate budget goals and financial deadlines into FocalPoint.","frontmatter":{"title":"YNAB Connector (Aspirational)","description":"Integrate budget goals and financial deadlines into FocalPoint."},"headers":[],"relativePath":"connectors/ynab.md","filePath":"connectors/ynab.md","lastUpdated":1777002546000}');
const _sfc_main = { name: "connectors/ynab.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="ynab-you-need-a-budget-connector" tabindex="-1">YNAB (You Need A Budget) Connector <a class="header-anchor" href="#ynab-you-need-a-budget-connector" aria-label="Permalink to &quot;YNAB (You Need A Budget) Connector&quot;">​</a></h1><p><em>This connector is aspirational. Status: Planned for Q4 2026.</em></p><p>The YNAB connector brings your budget goals and financial deadlines into FocalPoint, enabling financially-conscious focus rules.</p><h2 id="planned-features" tabindex="-1">Planned Features <a class="header-anchor" href="#planned-features" aria-label="Permalink to &quot;Planned Features&quot;">​</a></h2><ul><li><strong>Budget deadlines</strong>: Alert when budget review dates approach</li><li><strong>Overspend warnings</strong>: Trigger focus sessions before overspending</li><li><strong>Savings goals</strong>: Celebrate hitting savings milestones</li><li><strong>Monthly reviews</strong>: Schedule budget reflection rituals</li></ul><h2 id="example-rule" tabindex="-1">Example Rule <a class="header-anchor" href="#example-rule" aria-label="Permalink to &quot;Example Rule&quot;">​</a></h2><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Budget review ritual&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">trigger</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  event_type</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;ynab.budget.monthly_close&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">schedule_ritual</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;monthly_financial_review&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">coach_message</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Time to review this month&#39;s spending!&quot;</span></span></code></pre></div><h2 id="implementation-status" tabindex="-1">Implementation Status <a class="header-anchor" href="#implementation-status" aria-label="Permalink to &quot;Implementation Status&quot;">​</a></h2><ul><li>[ ] YNAB OAuth integration</li><li>[ ] Budget event subscription</li><li>[ ] Threshold configuration</li></ul><h2 id="roadmap" tabindex="-1">Roadmap <a class="header-anchor" href="#roadmap" aria-label="Permalink to &quot;Roadmap&quot;">​</a></h2><p>Part of the broader <strong>&quot;Financial Wellness Integration&quot;</strong> initiative.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("connectors/ynab.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const ynab = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  ynab as default
};
