import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Getting started","description":"FocalPoint documentation","frontmatter":{"title":"Getting started","description":"FocalPoint documentation"},"headers":[],"relativePath":"getting-started/index.md","filePath":"getting-started/index.md","lastUpdated":1776935227000}');
const _sfc_main = { name: "getting-started/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="getting-started" tabindex="-1">Getting started <a class="header-anchor" href="#getting-started" aria-label="Permalink to &quot;Getting started&quot;">​</a></h1><p>FocalPoint is a connector-first screen-time platform. To get useful value you need two things:</p><ol><li>The iOS app installed on your device (with <code>com.apple.developer.family-controls</code> entitlement).</li><li>At least one connector authenticated (Canvas LMS is the only shipping connector today).</li></ol><h2 id="paths" tabindex="-1">Paths <a class="header-anchor" href="#paths" aria-label="Permalink to &quot;Paths&quot;">​</a></h2><ul><li><a href="/getting-started/install-ios">Install on iOS</a> — build from source, pair device, install the <code>.ipa</code>, grant FamilyControls permission.</li><li><a href="/getting-started/first-rule">First rule walkthrough</a> — author, test, and deploy your first rule with Canvas.</li></ul><h2 id="prerequisites" tabindex="-1">Prerequisites <a class="header-anchor" href="#prerequisites" aria-label="Permalink to &quot;Prerequisites&quot;">​</a></h2><ul><li><strong>iOS 16+</strong> device (iPhone or iPad).</li><li><strong>Xcode 15+</strong> with a paid Apple Developer account.</li><li><strong>FamilyControls entitlement</strong> approved for your team id (Apple review is 1–4 weeks — submit early).</li><li><strong>Rust 1.82+</strong> and <strong>Task</strong> installed locally (see <a href="https://github.com/KooshaPari/FocalPoint/blob/main/CONTRIBUTING.md" target="_blank" rel="noreferrer"><code>CONTRIBUTING.md</code></a>).</li></ul><h2 id="no-dependencies-evaluation" tabindex="-1">No-dependencies evaluation <a class="header-anchor" href="#no-dependencies-evaluation" aria-label="Permalink to &quot;No-dependencies evaluation&quot;">​</a></h2><p>You can explore the rules engine and audit chain without a device:</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">task</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> test</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -p</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> focus-cli</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> rule</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> evaluate</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> examples/rules/assignment-focus.toml</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> \\</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  --events</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> examples/events/canvas-assignment-due.json</span></span></code></pre></div><p>This runs the rule against a fixture event stream and prints the decision trace — no iOS hardware required.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("getting-started/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
