import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"User Journey: Student on Canvas","description":"How students use FocalPoint to manage Canvas assignments and study workflows.","frontmatter":{"title":"User Journey: Student on Canvas","description":"How students use FocalPoint to manage Canvas assignments and study workflows."},"headers":[],"relativePath":"journeys/student-canvas.md","filePath":"journeys/student-canvas.md","lastUpdated":1777002552000}');
const _sfc_main = { name: "journeys/student-canvas.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="user-journey-student-on-canvas" tabindex="-1">User Journey: Student on Canvas <a class="header-anchor" href="#user-journey-student-on-canvas" aria-label="Permalink to &quot;User Journey: Student on Canvas&quot;">​</a></h1><h2 id="persona" tabindex="-1">Persona <a class="header-anchor" href="#persona" aria-label="Permalink to &quot;Persona&quot;">​</a></h2><p><strong>Name</strong>: Alice<br><strong>Context</strong>: CS major, 4 courses, Canvas + Apple Calendar<br><strong>Goal</strong>: Never miss a deadline; maintain consistent study habits<br><strong>Pain point</strong>: Procrastination on assignments; inconsistent focus time</p><h2 id="week-1-onboarding" tabindex="-1">Week 1: Onboarding <a class="header-anchor" href="#week-1-onboarding" aria-label="Permalink to &quot;Week 1: Onboarding&quot;">​</a></h2><h3 id="day-1-installation-setup-10-min" tabindex="-1">Day 1: Installation &amp; Setup (10 min) <a class="header-anchor" href="#day-1-installation-setup-10-min" aria-label="Permalink to &quot;Day 1: Installation &amp; Setup (10 min)&quot;">​</a></h3><p>Alice downloads FocalPoint on her iPhone 14. She:</p><ol><li>Grants FamilyControls entitlement (system prompt)</li><li>Skips optional connectors (just local rules for now)</li><li>Creates her first rule in-app: <ul><li><strong>Trigger</strong>: &quot;Daily at 8 AM&quot;</li><li><strong>Action</strong>: &quot;Show morning brief&quot;</li></ul></li><li>Sees the morning brief: empty (no Canvas yet)</li></ol><h3 id="day-2–3-canvas-connection-5-min" tabindex="-1">Day 2–3: Canvas Connection (5 min) <a class="header-anchor" href="#day-2–3-canvas-connection-5-min" aria-label="Permalink to &quot;Day 2–3: Canvas Connection (5 min)&quot;">​</a></h3><p>Alice links her Canvas account:</p><ol><li>Settings → Connectors → Canvas LMS → Enable</li><li>Signs in with her university SSO</li><li>Selects all 4 courses</li><li>Grants Canvas API permissions</li></ol><p>FocalPoint now syncs her assignments every 30 minutes.</p><p>Morning brief now shows:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>📚 Canvas assignments (next 2 weeks):</span></span>
<span class="line"><span>  • CS 101: Homework 3 (due Wed 11:59 PM)</span></span>
<span class="line"><span>  • CS 101: Midterm project (due in 10 days)</span></span>
<span class="line"><span>  • MATH 201: Problem set 5 (due Fri)</span></span></code></pre></div><h3 id="day-4–5-rule-creation-15-min" tabindex="-1">Day 4–5: Rule Creation (15 min) <a class="header-anchor" href="#day-4–5-rule-creation-15-min" aria-label="Permalink to &quot;Day 4–5: Rule Creation (15 min)&quot;">​</a></h3><p>Alice creates her first context-specific rule:</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Canvas assignment due in 24h - Study Focus&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">trigger</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">event_type</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;canvas.assignment.due_soon&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    hours_until</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">24</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">condition</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">time_window</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: { </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">start</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;08:00&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">end</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;23:59&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">not_in_focus</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">false</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">show_focus_view</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;study&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">block_app</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;com.tiktok.main&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;com.instagram.android&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">coach_message</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;{{event.title}} due in {{event.hours_until_due}} hours! Let&#39;s focus.&quot;</span></span></code></pre></div><p>She tests it by manually triggering the rule. TikTok gets blocked. ✓</p><h2 id="week-2–3-habit-formation" tabindex="-1">Week 2–3: Habit Formation <a class="header-anchor" href="#week-2–3-habit-formation" aria-label="Permalink to &quot;Week 2–3: Habit Formation&quot;">​</a></h2><h3 id="morning-ritual-2-min-daily" tabindex="-1">Morning Ritual (2 min daily) <a class="header-anchor" href="#morning-ritual-2-min-daily" aria-label="Permalink to &quot;Morning Ritual (2 min daily)&quot;">​</a></h3><p>Alice opens FocalPoint each morning at 7:30 AM:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>📊 Sleep: 7h 15m ✓</span></span>
<span class="line"><span>📅 Today: CS 101 lecture at 9 AM, MATH problem set due 11:59 PM</span></span>
<span class="line"><span>🎯 Focus opportunities:</span></span>
<span class="line"><span>   1. 8–9 AM: Review CS notes (60 min)</span></span>
<span class="line"><span>   2. 10 AM–12 PM: MATH problem set work (120 min)</span></span>
<span class="line"><span>🔥 Streak: 5 days</span></span></code></pre></div><p>She taps &quot;Start focus session&quot; and TikTok/Instagram are blocked until 2 PM.</p><h3 id="during-the-day" tabindex="-1">During the Day <a class="header-anchor" href="#during-the-day" aria-label="Permalink to &quot;During the Day&quot;">​</a></h3><p>Alice is in Slack. A notification appears:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>🎯 Canvas Assignment Alert</span></span>
<span class="line"><span>MATH 201 Problem set due in 4 hours!</span></span>
<span class="line"><span>👉 [Start focus] [Later] [Dismiss]</span></span></code></pre></div><p>She taps &quot;Start focus&quot; → 90-min focus timer starts → social apps blocked.</p><p>At 1 PM, she finishes the problem set and submits it in Canvas. Coachy reacts:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>💪 Submitted! You&#39;re ahead of schedule on MATH.</span></span>
<span class="line"><span>Keep the momentum going!</span></span></code></pre></div><h3 id="evening-reflection-5-min-daily" tabindex="-1">Evening Reflection (5 min daily) <a class="header-anchor" href="#evening-reflection-5-min-daily" aria-label="Permalink to &quot;Evening Reflection (5 min daily)&quot;">​</a></h3><p>At 10 PM, Evening Shutdown ritual appears:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>📊 TIME AUDIT</span></span>
<span class="line"><span>Focus time: 4h 30m (goal: 4h) ✓ +30m bonus!</span></span>
<span class="line"><span>Distraction time: 1h 15m (goal: &lt;2h) ✓</span></span>
<span class="line"><span></span></span>
<span class="line"><span>📚 Canvas Progress</span></span>
<span class="line"><span>Submitted: 2/8 assignments this week</span></span>
<span class="line"><span>Due soon: 2 (both &gt;=2 days away)</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Q: &quot;What blocked your focus?&quot;</span></span>
<span class="line"><span>A: [Procrastination on problem set]</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Q: &quot;Tomorrow&#39;s priority?&quot;</span></span>
<span class="line"><span>A: &quot;Start CS Midterm project&quot;</span></span>
<span class="line"><span></span></span>
<span class="line"><span>💭 Coachy: &quot;4.5h focus is great! </span></span>
<span class="line"><span>Procrastination hit you once—</span></span>
<span class="line"><span>consider tackling hard tasks first thing in the morning.&quot;</span></span>
<span class="line"><span></span></span>
<span class="line"><span>[Export audit] [Done]</span></span></code></pre></div><h2 id="week-4-streak-achievement" tabindex="-1">Week 4: Streak Achievement <a class="header-anchor" href="#week-4-streak-achievement" aria-label="Permalink to &quot;Week 4: Streak Achievement&quot;">​</a></h2><p>After 14 consecutive days of focus (matching her goal), Coachy celebrates:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>🔥 14-day streak!</span></span>
<span class="line"><span>You&#39;ve built a real habit. Keep it up! 🎉</span></span></code></pre></div><p>Alice shares her achievement on Instagram (voluntarily).</p><h2 id="month-2-advanced-usage" tabindex="-1">Month 2: Advanced Usage <a class="header-anchor" href="#month-2-advanced-usage" aria-label="Permalink to &quot;Month 2: Advanced Usage&quot;">​</a></h2><h3 id="rule-packs" tabindex="-1">Rule Packs <a class="header-anchor" href="#rule-packs" aria-label="Permalink to &quot;Rule Packs&quot;">​</a></h3><p>Alice imports the <strong>&quot;Student Focus Pack&quot;</strong> from the marketplace:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Includes 8 rules:</span></span>
<span class="line"><span>  • Canvas assignment deadline blocks</span></span>
<span class="line"><span>  • Morning study prep ritual</span></span>
<span class="line"><span>  • Exam week intense focus mode</span></span>
<span class="line"><span>  • Sleep wellness checks</span></span>
<span class="line"><span>  • Procrastination detection</span></span></code></pre></div><p>She customizes the &quot;Exam week intense focus mode&quot; rule:</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># During exam week, block ALL social apps + calls</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">trigger</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">schedule</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Mon–Fri, Apr 15–19, 8 AM–11 PM&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">block_category</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Games&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Social Media&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Communication&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">mute_notifications</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">coach_message</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Exam week focus mode ON. You&#39;ve got this!&quot;</span></span></code></pre></div><h3 id="study-streaks" tabindex="-1">Study Streaks <a class="header-anchor" href="#study-streaks" aria-label="Permalink to &quot;Study Streaks&quot;">​</a></h3><p>Over the semester, Alice&#39;s focus streak reaches 67 days. She earned:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>⭐ 5,000 wallet points</span></span>
<span class="line"><span>🏆 &quot;Consistent Studier&quot; achievement</span></span>
<span class="line"><span>📜 Audit chain: 67 consecutive days</span></span></code></pre></div><p>She can optionally export her audit chain to share with parents or advisors.</p><h3 id="coaching-personalization" tabindex="-1">Coaching Personalization <a class="header-anchor" href="#coaching-personalization" aria-label="Permalink to &quot;Coaching Personalization&quot;">​</a></h3><p>Coachy learns Alice&#39;s patterns:</p><ul><li>She procrastinates most on coding assignments → Suggest Pomodoro timer</li><li>She studies best 8–11 AM → Suggest focus blocks in that window</li><li>Her energy dips after 3 PM → Less aggressive coaching in evening</li></ul><h2 id="pain-point-resolution" tabindex="-1">Pain Point Resolution <a class="header-anchor" href="#pain-point-resolution" aria-label="Permalink to &quot;Pain Point Resolution&quot;">​</a></h2><h3 id="procrastination-on-midterm" tabindex="-1">Procrastination on Midterm <a class="header-anchor" href="#procrastination-on-midterm" aria-label="Permalink to &quot;Procrastination on Midterm&quot;">​</a></h3><p>In week 5, Alice delays starting the CS Midterm. Coachy detects:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>💭 &quot;I noticed you haven&#39;t started the Midterm project yet, </span></span>
<span class="line"><span>and it&#39;s due in 5 days. That&#39;s usually when procrastination hits. </span></span>
<span class="line"><span>Want to break it down into smaller steps?&quot;</span></span>
<span class="line"><span></span></span>
<span class="line"><span>[Yes, help!] [I&#39;ll start tomorrow] [Let me think]</span></span></code></pre></div><p>Alice taps &quot;Yes, help!&quot; and Coachy suggests:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>1. Read project spec (30 min) — Today, 3 PM</span></span>
<span class="line"><span>2. Set up Git repo (15 min) — Tomorrow morning</span></span>
<span class="line"><span>3. Implement part 1 (2 hours) — Tomorrow, after lecture</span></span></code></pre></div><p>Alice marks each subtask complete. When she finishes part 1 on schedule, Coachy celebrates—reinforcing momentum.</p><h2 id="semester-end" tabindex="-1">Semester End <a class="header-anchor" href="#semester-end" aria-label="Permalink to &quot;Semester End&quot;">​</a></h2><p>Alice&#39;s final stats:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Total focus time: 187 hours</span></span>
<span class="line"><span>Assignments on time: 32/32 ✓</span></span>
<span class="line"><span>Highest streak: 67 consecutive days</span></span>
<span class="line"><span>GPA benefit: +0.3 (attributed to consistent study)</span></span></code></pre></div><p>She exports her audit chain as a PDF summary to share with her parents.</p><h2 id="key-moments" tabindex="-1">Key Moments <a class="header-anchor" href="#key-moments" aria-label="Permalink to &quot;Key Moments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Moment</th><th>Emotion</th><th>Outcome</th></tr></thead><tbody><tr><td>Rule blocking TikTok successfully</td><td>Pride</td><td>Keeps using FocalPoint</td></tr><tr><td>7-day streak celebration</td><td>Excitement</td><td>Shares with friends</td></tr><tr><td>Procrastination detection nudge</td><td>Relief</td><td>Breaks down big task</td></tr><tr><td>67-day streak achievement</td><td>Joy</td><td>Becomes advocate; recommends to classmates</td></tr></tbody></table><h2 id="success-criteria" tabindex="-1">Success Criteria <a class="header-anchor" href="#success-criteria" aria-label="Permalink to &quot;Success Criteria&quot;">​</a></h2><p>✓ Alice never missed a Canvas deadline after week 1<br> ✓ Consistent 3–4 hour daily focus (vs. 1–2 hour baseline)<br> ✓ Procrastination incidents dropped from 3/week to 1/month<br> ✓ Actively uses FocalPoint 6 days/week<br> ✓ Imported 1 rule pack, created 2 custom rules</p><p>See also: <a href="./../connectors/canvas">Canvas Connector Guide</a>, <a href="./../rules/dsl">Rules Reference</a>, <a href="./../rituals/">Rituals</a></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("journeys/student-canvas.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const studentCanvas = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  studentCanvas as default
};
