import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"User Journey: Developer with GitHub","description":"How developers use FocalPoint to manage PR reviews, issue assignments, and coding streaks.","frontmatter":{"title":"User Journey: Developer with GitHub","description":"How developers use FocalPoint to manage PR reviews, issue assignments, and coding streaks."},"headers":[],"relativePath":"journeys/developer-github.md","filePath":"journeys/developer-github.md","lastUpdated":1777002552000}');
const _sfc_main = { name: "journeys/developer-github.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="user-journey-developer-with-github" tabindex="-1">User Journey: Developer with GitHub <a class="header-anchor" href="#user-journey-developer-with-github" aria-label="Permalink to &quot;User Journey: Developer with GitHub&quot;">​</a></h1><h2 id="persona" tabindex="-1">Persona <a class="header-anchor" href="#persona" aria-label="Permalink to &quot;Persona&quot;">​</a></h2><p><strong>Name</strong>: Bob<br><strong>Context</strong>: Full-stack engineer, 3 active repos, GitHub organization owner<br><strong>Goal</strong>: Deep focus for code review and feature work; ship quality code<br><strong>Pain point</strong>: Notifications interrupt flow; context switching between repos</p><h2 id="week-1-onboarding" tabindex="-1">Week 1: Onboarding <a class="header-anchor" href="#week-1-onboarding" aria-label="Permalink to &quot;Week 1: Onboarding&quot;">​</a></h2><h3 id="day-1-installation-8-min" tabindex="-1">Day 1: Installation (8 min) <a class="header-anchor" href="#day-1-installation-8-min" aria-label="Permalink to &quot;Day 1: Installation (8 min)&quot;">​</a></h3><p>Bob downloads FocalPoint. He:</p><ol><li>Grants FamilyControls entitlement</li><li>Creates a basic rule: &quot;Block Slack during coding sessions&quot;</li><li>Skips connectors (explores later)</li></ol><h3 id="day-2–3-github-connection-5-min" tabindex="-1">Day 2–3: GitHub Connection (5 min) <a class="header-anchor" href="#day-2–3-github-connection-5-min" aria-label="Permalink to &quot;Day 2–3: GitHub Connection (5 min)&quot;">​</a></h3><p>Bob links his GitHub account:</p><ol><li>Settings → Connectors → GitHub → Enable</li><li>OAuth redirects to GitHub</li><li>Selects repos to monitor: <code>myorg/backend</code>, <code>myorg/frontend</code>, <code>myorg/cli</code></li><li>Grants API permissions</li></ol><p>FocalPoint now tracks:</p><ul><li>PR ready for review notifications</li><li>Issue assignments</li><li>Milestone deadlines</li><li>Commit activity</li></ul><h3 id="day-4–5-code-review-rule-10-min" tabindex="-1">Day 4–5: Code Review Rule (10 min) <a class="header-anchor" href="#day-4–5-code-review-rule-10-min" aria-label="Permalink to &quot;Day 4–5: Code Review Rule (10 min)&quot;">​</a></h3><p>Bob creates a custom rule for PR reviews:</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;PR Review Focus Session&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">trigger</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">event_type</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;github.pr.ready_for_review&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    repository</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;myorg/backend&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">condition</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">time_window</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: { </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">start</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;10:00&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">end</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;12:00&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">not_in_focus</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">false</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">show_focus_view</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;code_review&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">block_app</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">      - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;com.slack&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">      - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;com.discord&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">      - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;com.figma.mac&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">set_focus_duration</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;60 minutes&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">coach_message</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;PR from {{event.author}}: {{event.title}}&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">log_audit</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Started PR review session&quot;</span></span></code></pre></div><p>He tests it. Slack gets muted. ✓</p><h2 id="week-2–3-deep-work-establishment" tabindex="-1">Week 2–3: Deep Work Establishment <a class="header-anchor" href="#week-2–3-deep-work-establishment" aria-label="Permalink to &quot;Week 2–3: Deep Work Establishment&quot;">​</a></h2><h3 id="morning-check-in-3-min" tabindex="-1">Morning Check-in (3 min) <a class="header-anchor" href="#morning-check-in-3-min" aria-label="Permalink to &quot;Morning Check-in (3 min)&quot;">​</a></h3><p>Bob opens FocalPoint at 9 AM:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>📊 GitHub Activity:</span></span>
<span class="line"><span>  • 3 PRs waiting for review</span></span>
<span class="line"><span>  • 1 new issue assigned</span></span>
<span class="line"><span>  • Milestone &quot;v1.2&quot; due in 5 days</span></span>
<span class="line"><span></span></span>
<span class="line"><span>📅 Schedule:</span></span>
<span class="line"><span>  • 10 AM: Team standup</span></span>
<span class="line"><span>  • 1 PM: Architecture discussion</span></span>
<span class="line"><span></span></span>
<span class="line"><span>🎯 Focus opportunities:</span></span>
<span class="line"><span>  1. 9–10 AM: Quick PR review (60 min)</span></span>
<span class="line"><span>  2. 11 AM–1 PM: Feature work (120 min)</span></span>
<span class="line"><span>  3. 2 PM: Async code review (90 min)</span></span>
<span class="line"><span></span></span>
<span class="line"><span>🔥 Streak: 3 days</span></span></code></pre></div><h3 id="pr-review-session-10-am" tabindex="-1">PR Review Session (10 AM) <a class="header-anchor" href="#pr-review-session-10-am" aria-label="Permalink to &quot;PR Review Session (10 AM)&quot;">​</a></h3><p>A notification appears:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>👀 PR Ready for Review</span></span>
<span class="line"><span>Backend team: &quot;Add async database pooling&quot;</span></span>
<span class="line"><span>Comments: 2 | Changes: 450 lines</span></span>
<span class="line"><span>👉 [Start review] [Later] [Dismiss]</span></span></code></pre></div><p>Bob taps &quot;Start review&quot;:</p><ul><li>Slack is muted</li><li>Focus timer starts (60 min)</li><li>GitHub opens in focus mode (other apps dimmed)</li><li>Coachy watches for context switching</li></ul><p>Bob spends 55 minutes reviewing the PR. He provides detailed feedback. Once done, Coachy celebrates:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>💪 Thorough review! 6 comments, 2 suggestions.</span></span>
<span class="line"><span>Quality work!</span></span></code></pre></div><h3 id="afternoon-feature-work-2-pm" tabindex="-1">Afternoon Feature Work (2 PM) <a class="header-anchor" href="#afternoon-feature-work-2-pm" aria-label="Permalink to &quot;Afternoon Feature Work (2 PM)&quot;">​</a></h3><p>Bob starts implementing a new feature. He manually enables a longer focus session:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>🎯 Feature: &quot;Add webhook support&quot;</span></span>
<span class="line"><span>Duration: 180 minutes</span></span>
<span class="line"><span>Status: In progress</span></span></code></pre></div><p>After 90 minutes, Coachy suggests:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>⏰ You&#39;ve been focused for 90 minutes. </span></span>
<span class="line"><span>Time for a break?</span></span>
<span class="line"><span>[Take 15 min break] [Keep going] [End session]</span></span></code></pre></div><p>Bob taps &quot;Take 15 min break&quot;. He steps away, comes back, and resumes focus. After 180 minutes, the session ends and Coachy celebrates:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>🔥 3-hour focus session completed!</span></span>
<span class="line"><span>You&#39;re in the zone. </span></span>
<span class="line"><span>Take a real break now—you&#39;ve earned it!</span></span></code></pre></div><h3 id="evening-reflection-5-min" tabindex="-1">Evening Reflection (5 min) <a class="header-anchor" href="#evening-reflection-5-min" aria-label="Permalink to &quot;Evening Reflection (5 min)&quot;">​</a></h3><p>At 7 PM, Bob completes the Evening Shutdown ritual:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>📊 CODE ACTIVITY</span></span>
<span class="line"><span>Focus time: 4h 30m (goal: 4h) ✓ +30m bonus</span></span>
<span class="line"><span>PR reviews: 2 completed</span></span>
<span class="line"><span>Commits: 3 feature work</span></span>
<span class="line"><span>Code quality: 95% (linted, tested)</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Q: &quot;What blocked your focus?&quot;</span></span>
<span class="line"><span>A: [Brief Slack distraction at 11 AM]</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Q: &quot;Tomorrow&#39;s priority?&quot;</span></span>
<span class="line"><span>A: &quot;Finish webhook feature + write tests&quot;</span></span>
<span class="line"><span></span></span>
<span class="line"><span>💭 Coachy: &quot;Strong day! </span></span>
<span class="line"><span>You nailed those PRs and got deep into the webhook work.</span></span>
<span class="line"><span>Tomorrow, consider disabling Slack entirely during feature work.&quot;</span></span>
<span class="line"><span></span></span>
<span class="line"><span>[Export audit] [Done]</span></span></code></pre></div><h2 id="week-4-milestone-tracking" tabindex="-1">Week 4: Milestone Tracking <a class="header-anchor" href="#week-4-milestone-tracking" aria-label="Permalink to &quot;Week 4: Milestone Tracking&quot;">​</a></h2><h3 id="milestone-deadline-approaching" tabindex="-1">Milestone Deadline Approaching <a class="header-anchor" href="#milestone-deadline-approaching" aria-label="Permalink to &quot;Milestone Deadline Approaching&quot;">​</a></h3><p>Coachy detects that the &quot;v1.2&quot; milestone is due in 2 days:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>⚠️ Milestone &quot;v1.2&quot; due in 2 days!</span></span>
<span class="line"><span>Remaining items: 3 PRs to review, 1 feature to finish</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Want to schedule intensive focus blocks for the next 2 days?</span></span>
<span class="line"><span>[Yes, schedule] [I have it under control] [Snooze]</span></span></code></pre></div><p>Bob taps &quot;Yes, schedule&quot;. FocalPoint adds:</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">trigger</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">schedule</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;tomorrow 9 AM–6 PM&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">show_focus_view</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;deadline_sprint&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">block_category</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Games&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Social Media&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">limit_notifications</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;urgent_only&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">coach_message</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Milestone sprint day 1. Let&#39;s ship!&quot;</span></span></code></pre></div><h3 id="deadline-day" tabindex="-1">Deadline Day <a class="header-anchor" href="#deadline-day" aria-label="Permalink to &quot;Deadline Day&quot;">​</a></h3><p>The next day, Bob focuses intensively:</p><ul><li>9–12 PM: Review 2 PRs</li><li>1–3 PM: Lunch + refocus</li><li>3–6 PM: Finish webhook feature + tests</li></ul><p>By end of day, all v1.2 PRs are merged. Coachy celebrates:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>🎉 MILESTONE SHIPPED!</span></span>
<span class="line"><span>v1.2 is live. Great work, team!</span></span>
<span class="line"><span>Your contribution: 4 PRs reviewed, 1 major feature.</span></span></code></pre></div><h2 id="month-2-advanced-usage" tabindex="-1">Month 2: Advanced Usage <a class="header-anchor" href="#month-2-advanced-usage" aria-label="Permalink to &quot;Month 2: Advanced Usage&quot;">​</a></h2><h3 id="custom-coaching-rules" tabindex="-1">Custom Coaching Rules <a class="header-anchor" href="#custom-coaching-rules" aria-label="Permalink to &quot;Custom Coaching Rules&quot;">​</a></h3><p>Bob creates a personalized coaching rule:</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Pomodoro Pairing&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">trigger</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">event_type</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;github.pr.review.long_session&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    duration_minutes</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">120</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">coach_message</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;You&#39;ve been reviewing for 2 hours.</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    Time for a Pomodoro break?</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    [25-min timer] [Keep going] [End session]&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">schedule_break</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;25 minutes&quot;</span></span></code></pre></div><h3 id="commit-streaks" tabindex="-1">Commit Streaks <a class="header-anchor" href="#commit-streaks" aria-label="Permalink to &quot;Commit Streaks&quot;">​</a></h3><p>Over 45 days, Bob maintains a commit streak. His audit chain shows:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>45-day commit streak</span></span>
<span class="line"><span>Commits: 187</span></span>
<span class="line"><span>PR reviews: 52</span></span>
<span class="line"><span>Avg code review time: 18 min</span></span>
<span class="line"><span>Code quality score: 96%</span></span></code></pre></div><p>He shares this summary with his team during sprint retro.</p><h3 id="github-actions-integration-aspirational" tabindex="-1">GitHub Actions Integration (Aspirational) <a class="header-anchor" href="#github-actions-integration-aspirational" aria-label="Permalink to &quot;GitHub Actions Integration (Aspirational)&quot;">​</a></h3><p>In v1.1, Bob will be able to link FocalPoint to his GitHub Actions CI/CD:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Trigger: &quot;CI pipeline failed&quot;</span></span>
<span class="line"><span>Action: &quot;Urgent focus block for debugging&quot;</span></span></code></pre></div><p>For now, he manually enables focus when debugging fails.</p><h2 id="pain-point-context-switching" tabindex="-1">Pain Point: Context Switching <a class="header-anchor" href="#pain-point-context-switching" aria-label="Permalink to &quot;Pain Point: Context Switching&quot;">​</a></h2><h3 id="situation" tabindex="-1">Situation <a class="header-anchor" href="#situation" aria-label="Permalink to &quot;Situation&quot;">​</a></h3><p>Bob works on 3 repos simultaneously. He&#39;s in:</p><ul><li>Reviewing backend PR (repo A)</li><li>Implementing feature (repo B)</li><li>Debugging CLI test (repo C)</li></ul><p>After each repo switch, FocalPoint notices:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>⚠️ Context switched 6 times in 45 minutes.</span></span>
<span class="line"><span>This often breaks flow. </span></span>
<span class="line"><span></span></span>
<span class="line"><span>Consider:</span></span>
<span class="line"><span>  1. Batch repo tasks (all backend PRs, then feature work)</span></span>
<span class="line"><span>  2. Set a &quot;single-repo focus&quot; rule for feature work</span></span>
<span class="line"><span>  3. Schedule reviews in a dedicated time block (10 AM)</span></span>
<span class="line"><span></span></span>
<span class="line"><span>[Create focus rule] [Later]</span></span></code></pre></div><p>Bob taps &quot;Create focus rule&quot;. FocalPoint drafts:</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Single-Repo Focus: Feature Work&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">trigger</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">user_initiated</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">show_focus_view</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;feature_work&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">whitelist_app</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;GitHub&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;VSCode&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Terminal&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">block_category</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Games&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Social Media&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">coach_message</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Feature focus: repo B only.</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    Batch reviews for 2 PM.&quot;</span></span></code></pre></div><p>Bob customizes and saves it. Over the next week, context switches drop from 6 to 2 per focus session.</p><h2 id="success-metrics-month-2" tabindex="-1">Success Metrics (Month 2) <a class="header-anchor" href="#success-metrics-month-2" aria-label="Permalink to &quot;Success Metrics (Month 2)&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Focus sessions: 24</span></span>
<span class="line"><span>Avg focus duration: 87 minutes</span></span>
<span class="line"><span>PR review quality: +12% (measured by feedback scores)</span></span>
<span class="line"><span>Time-to-merge: -15% (faster reviews)</span></span>
<span class="line"><span>Commit streak: 45 days</span></span>
<span class="line"><span>Code quality: 96%</span></span>
<span class="line"><span>Context switches per session: 2 (was 6)</span></span></code></pre></div><p>Bob tells his team: &quot;FocalPoint made code review better. I&#39;m actually thoughtful instead of skimming.&quot;</p><h2 id="key-moments" tabindex="-1">Key Moments <a class="header-anchor" href="#key-moments" aria-label="Permalink to &quot;Key Moments&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Moment</th><th>Emotion</th><th>Outcome</th></tr></thead><tbody><tr><td>First PR review in focus mode</td><td>Calm/focused</td><td>Provides better feedback</td></tr><tr><td>Coachy detects context switching</td><td>Surprised</td><td>Changes workflow for better focus</td></tr><tr><td>Milestone shipped on time</td><td>Pride</td><td>Recommends to teammates</td></tr><tr><td>45-day commit streak</td><td>Motivated</td><td>Continues using FocalPoint</td></tr></tbody></table><p>See also: <a href="./../connectors/github">GitHub Connector Guide</a>, <a href="./../rules/dsl">Rules Reference</a>, <a href="./../getting-started/first-rule">Focus Modes</a></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("journeys/developer-github.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const developerGithub = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  developerGithub as default
};
