import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Coachy Personality Guide","description":"Tone of voice, communication patterns, and customization options.","frontmatter":{"title":"Coachy Personality Guide","description":"Tone of voice, communication patterns, and customization options."},"headers":[],"relativePath":"mascot/personality.md","filePath":"mascot/personality.md","lastUpdated":1777002546000}');
const _sfc_main = { name: "mascot/personality.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="coachy-personality-guide" tabindex="-1">Coachy Personality Guide <a class="header-anchor" href="#coachy-personality-guide" aria-label="Permalink to &quot;Coachy Personality Guide&quot;">​</a></h1><h2 id="core-voice" tabindex="-1">Core Voice <a class="header-anchor" href="#core-voice" aria-label="Permalink to &quot;Core Voice&quot;">​</a></h2><p>Coachy speaks like a friend, not a manager. Think:</p><ul><li>✓ &quot;You&#39;ve got this—let&#39;s crush this assignment&quot;</li><li>✗ &quot;You must complete your assignments on time&quot;</li><li>✓ &quot;Looks like you need some sleep. Want an early shutdown?&quot;</li><li>✗ &quot;You are not getting enough sleep&quot;</li></ul><h2 id="communication-patterns" tabindex="-1">Communication Patterns <a class="header-anchor" href="#communication-patterns" aria-label="Permalink to &quot;Communication Patterns&quot;">​</a></h2><h3 id="positive-reinforcement" tabindex="-1">Positive Reinforcement <a class="header-anchor" href="#positive-reinforcement" aria-label="Permalink to &quot;Positive Reinforcement&quot;">​</a></h3><p>When user achieves a goal:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>&quot;🎉 7-day streak! You&#39;re building real habits.&quot;</span></span>
<span class="line"><span>&quot;⭐ Great focus session—90 minutes straight!&quot;</span></span>
<span class="line"><span>&quot;💪 Submitted 3 assignments early this week. Nice planning!&quot;</span></span></code></pre></div><h3 id="gentle-nudges" tabindex="-1">Gentle Nudges <a class="header-anchor" href="#gentle-nudges" aria-label="Permalink to &quot;Gentle Nudges&quot;">​</a></h3><p>When user is drifting:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>&quot;👀 Been on TikTok for 30 mins. Ready to switch gears?&quot;</span></span>
<span class="line"><span>&quot;🤔 Haven&#39;t started that essay yet? Want to break it down?&quot;</span></span>
<span class="line"><span>&quot;💭 Your sleep debt is climbing. Could use some rest tonight.&quot;</span></span></code></pre></div><h3 id="celebration-specificity" tabindex="-1">Celebration Specificity <a class="header-anchor" href="#celebration-specificity" aria-label="Permalink to &quot;Celebration Specificity&quot;">​</a></h3><p>Always mention what you&#39;re celebrating:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>✓ &quot;5-day focus streak on your Canvas assignments!&quot;</span></span>
<span class="line"><span>✗ &quot;You&#39;re awesome!&quot;</span></span></code></pre></div><h3 id="emotional-awareness" tabindex="-1">Emotional Awareness <a class="header-anchor" href="#emotional-awareness" aria-label="Permalink to &quot;Emotional Awareness&quot;">​</a></h3><p>Detect and respond to emotional state:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>If user keeps dismissing focus sessions:</span></span>
<span class="line"><span>&quot;I notice you&#39;re not feeling the focus thing right now. </span></span>
<span class="line"><span> What&#39;s getting in the way?&quot;</span></span>
<span class="line"><span></span></span>
<span class="line"><span>If user hits a big goal:</span></span>
<span class="line"><span>&quot;This is your biggest study streak yet. </span></span>
<span class="line"><span> How are you feeling about it?&quot;</span></span></code></pre></div><h2 id="frequency-strategies" tabindex="-1">Frequency Strategies <a class="header-anchor" href="#frequency-strategies" aria-label="Permalink to &quot;Frequency Strategies&quot;">​</a></h2><h3 id="rare-2–3-day" tabindex="-1">Rare (2–3/day) <a class="header-anchor" href="#rare-2–3-day" aria-label="Permalink to &quot;Rare (2–3/day)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Morning: Study reminders</span></span>
<span class="line"><span>Evening: Sleep check-in</span></span></code></pre></div><h3 id="balanced-5–8-day" tabindex="-1">Balanced (5–8/day) <a class="header-anchor" href="#balanced-5–8-day" aria-label="Permalink to &quot;Balanced (5–8/day)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Morning: Intention setting</span></span>
<span class="line"><span>Midday: Assignment reminder</span></span>
<span class="line"><span>Afternoon: Focus offer</span></span>
<span class="line"><span>Evening: Reflection</span></span></code></pre></div><h3 id="supportive-10–15-day" tabindex="-1">Supportive (10–15/day) <a class="header-anchor" href="#supportive-10–15-day" aria-label="Permalink to &quot;Supportive (10–15/day)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Frequent encouragement, achievement notifications, </span></span>
<span class="line"><span>helpful nudges, progress updates</span></span></code></pre></div><h3 id="assertive-20-day" tabindex="-1">Assertive (20+/day) <a class="header-anchor" href="#assertive-20-day" aria-label="Permalink to &quot;Assertive (20+/day)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Aggressive reminders, frequent check-ins, </span></span>
<span class="line"><span>detailed progress tracking, challenge prompts</span></span></code></pre></div><h2 id="handling-failures" tabindex="-1">Handling Failures <a class="header-anchor" href="#handling-failures" aria-label="Permalink to &quot;Handling Failures&quot;">​</a></h2><p>Never shame. Always offer a path forward:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>✓ &quot;Missed your focus block. No big deal—habit takes time. </span></span>
<span class="line"><span>   Try again tomorrow?&quot;</span></span>
<span class="line"><span></span></span>
<span class="line"><span>✗ &quot;You failed again.&quot;</span></span></code></pre></div><h2 id="personalization-examples" tabindex="-1">Personalization Examples <a class="header-anchor" href="#personalization-examples" aria-label="Permalink to &quot;Personalization Examples&quot;">​</a></h2><h3 id="student-on-canvas" tabindex="-1">Student on Canvas <a class="header-anchor" href="#student-on-canvas" aria-label="Permalink to &quot;Student on Canvas&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Morning: &quot;Hey Alice! You have 2 assignments due this week. </span></span>
<span class="line"><span>         Start with the Midterm Project?&quot;</span></span>
<span class="line"><span>Afternoon: &quot;Canvas deadline in 4 hours. Focus time?&quot;</span></span>
<span class="line"><span>Evening: &quot;Great work on the essay! Want to review it once more?&quot;</span></span></code></pre></div><h3 id="developer-on-github" tabindex="-1">Developer on GitHub <a class="header-anchor" href="#developer-on-github" aria-label="Permalink to &quot;Developer on GitHub&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Morning: &quot;3 PRs waiting for review. Ready to dive in?&quot;</span></span>
<span class="line"><span>Afternoon: &quot;You&#39;ve reviewed 5 PRs today. Break time?&quot;</span></span>
<span class="line"><span>Evening: &quot;Shipped a feature! Nice work on the commit messages.&quot;</span></span></code></pre></div><h3 id="parent-via-family-sharing" tabindex="-1">Parent (via Family Sharing) <a class="header-anchor" href="#parent-via-family-sharing" aria-label="Permalink to &quot;Parent (via Family Sharing)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Afternoon: &quot;Kids, homework time in 15 mins. Who&#39;s ready?&quot;</span></span>
<span class="line"><span>Evening: &quot;Great focus session! All assignments done. </span></span>
<span class="line"><span>         Time for a game or show?&quot;</span></span></code></pre></div><h2 id="when-to-stay-quiet" tabindex="-1">When to Stay Quiet <a class="header-anchor" href="#when-to-stay-quiet" aria-label="Permalink to &quot;When to Stay Quiet&quot;">​</a></h2><p>Coachy respects:</p><ul><li>Do-not-disturb windows (after 10 PM)</li><li>Focus sessions (no interruptions)</li><li>Exam days (minimal messaging)</li><li>Vacation/break periods (automatic pause)</li></ul><p>Users control silence preferences in Settings → Coaching → Availability.</p><h2 id="tone-customization" tabindex="-1">Tone Customization <a class="header-anchor" href="#tone-customization" aria-label="Permalink to &quot;Tone Customization&quot;">​</a></h2><h3 id="professional" tabindex="-1">Professional <a class="header-anchor" href="#professional" aria-label="Permalink to &quot;Professional&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>&quot;Focus session starting: 90 minutes, </span></span>
<span class="line"><span> {{app_list}} blocked, notifications muted.&quot;</span></span></code></pre></div><h3 id="casual" tabindex="-1">Casual <a class="header-anchor" href="#casual" aria-label="Permalink to &quot;Casual&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>&quot;Ready to lock in? 90 min, zero distractions.&quot;</span></span></code></pre></div><h3 id="playful" tabindex="-1">Playful <a class="header-anchor" href="#playful" aria-label="Permalink to &quot;Playful&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>&quot;⏰ Let&#39;s go, champ! 90-min focus frenzy time!&quot;</span></span></code></pre></div><h2 id="implementation-notes" tabindex="-1">Implementation Notes <a class="header-anchor" href="#implementation-notes" aria-label="Permalink to &quot;Implementation Notes&quot;">​</a></h2><p>All Coachy messages are:</p><ol><li><strong>Rule-based</strong>: Generated by rule engine, not ML</li><li><strong>Auditable</strong>: Every message logged to audit chain</li><li><strong>Customizable</strong>: User can adjust frequency, tone, emoji</li><li><strong>Local</strong>: No cloud coaching model; runs on-device</li><li><strong>Respectful</strong>: Respects DND times and user preferences</li></ol><p>See <strong><a href="./character-sheet">Character Sheet</a></strong> for design specs and emoji library.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("mascot/personality.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const personality = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  personality as default
};
