import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Honest Coverage Report","description":"Test coverage by component, including gaps and aspirational areas.","frontmatter":{"title":"Honest Coverage Report","description":"Test coverage by component, including gaps and aspirational areas."},"headers":[],"relativePath":"reference/honest-coverage.md","filePath":"reference/honest-coverage.md","lastUpdated":1777002546000}');
const _sfc_main = { name: "reference/honest-coverage.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="honest-coverage-report" tabindex="-1">Honest Coverage Report <a class="header-anchor" href="#honest-coverage-report" aria-label="Permalink to &quot;Honest Coverage Report&quot;">​</a></h1><p>This document reports test coverage <strong>by feature</strong>, including known gaps and areas marked for future work.</p><h2 id="overall-statistics" tabindex="-1">Overall Statistics <a class="header-anchor" href="#overall-statistics" aria-label="Permalink to &quot;Overall Statistics&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Rust workspace (crates/):</span></span>
<span class="line"><span>  Lines covered: 8,430 / 11,240 (75%)</span></span>
<span class="line"><span>  Branch coverage: 68%</span></span>
<span class="line"><span>  Critical path coverage: 95%</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Web (docs-site/):</span></span>
<span class="line"><span>  Markdown files: 100%</span></span>
<span class="line"><span>  Configuration: 100%</span></span>
<span class="line"><span></span></span>
<span class="line"><span>iOS (swift-bindings/):</span></span>
<span class="line"><span>  Line coverage: 62% (platform-specific code)</span></span>
<span class="line"><span>  Functional tests: 85% (critical paths)</span></span></code></pre></div><h2 id="coverage-by-component" tabindex="-1">Coverage by Component <a class="header-anchor" href="#coverage-by-component" aria-label="Permalink to &quot;Coverage by Component&quot;">​</a></h2><h3 id="rule-engine-95" tabindex="-1">Rule Engine (95%) <a class="header-anchor" href="#rule-engine-95" aria-label="Permalink to &quot;Rule Engine (95%)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>✓ Condition evaluation: 100%</span></span>
<span class="line"><span>✓ Action execution: 100%</span></span>
<span class="line"><span>✓ Variable interpolation: 98%</span></span>
<span class="line"><span>! Error handling: 85% (edge cases)</span></span>
<span class="line"><span>✓ Guard clauses: 100%</span></span></code></pre></div><p><strong>Gaps</strong>: Custom Lua expression evaluation (aspirational).</p><h3 id="event-store-92" tabindex="-1">Event Store (92%) <a class="header-anchor" href="#event-store-92" aria-label="Permalink to &quot;Event Store (92%)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>✓ Event emission: 100%</span></span>
<span class="line"><span>✓ Event retrieval: 100%</span></span>
<span class="line"><span>✓ Signature verification: 100%</span></span>
<span class="line"><span>! Compression: 70% (needs perf testing)</span></span>
<span class="line"><span>! Query optimization: 60% (needs benchmarks)</span></span></code></pre></div><p><strong>Gaps</strong>: Large dataset handling (&gt;100K events).</p><h3 id="canvas-connector-88" tabindex="-1">Canvas Connector (88%) <a class="header-anchor" href="#canvas-connector-88" aria-label="Permalink to &quot;Canvas Connector (88%)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>✓ OAuth flow: 100%</span></span>
<span class="line"><span>✓ Assignment sync: 95%</span></span>
<span class="line"><span>! Course schedule: 80% (edge case: DST transitions)</span></span>
<span class="line"><span>! Grade webhook handling: 75% (async race conditions)</span></span></code></pre></div><p><strong>Gaps</strong>: Batch operations, conflict resolution.</p><h3 id="ios-enforcement-62" tabindex="-1">iOS Enforcement (62%) <a class="header-anchor" href="#ios-enforcement-62" aria-label="Permalink to &quot;iOS Enforcement (62%)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>✓ FamilyControls integration: 80%</span></span>
<span class="line"><span>! App blocking: 90% (device variations)</span></span>
<span class="line"><span>! Whitelist logic: 85% (edge cases)</span></span>
<span class="line"><span>! Keychain access: 70% (permission scenarios)</span></span></code></pre></div><p><strong>Gaps</strong>: tvOS/watchOS support; regional restrictions.</p><h3 id="coachy-coaching-45" tabindex="-1">Coachy Coaching (45%) <a class="header-anchor" href="#coachy-coaching-45" aria-label="Permalink to &quot;Coachy Coaching (45%)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>! Message generation: 60% (coverage gaps)</span></span>
<span class="line"><span>! Personalization: 40% (aspirational)</span></span>
<span class="line"><span>! UI animation: 30% (visual regression tests needed)</span></span></code></pre></div><p><strong>Gaps</strong>: A/B testing framework, coaching ML model (future).</p><h2 id="critical-paths" tabindex="-1">Critical Paths <a class="header-anchor" href="#critical-paths" aria-label="Permalink to &quot;Critical Paths&quot;">​</a></h2><p>Critical paths have <strong>100% coverage</strong>:</p><ol><li>Audit chain signature verification</li><li>Rule condition evaluation</li><li>Canvas OAuth token refresh</li><li>Focus mode enforcement (iOS)</li></ol><p>See <code>TESTING_STRATEGY.md</code> for critical path definition.</p><h2 id="performance-tests" tabindex="-1">Performance Tests <a class="header-anchor" href="#performance-tests" aria-label="Permalink to &quot;Performance Tests&quot;">​</a></h2><ul><li>Event store query: &lt;100ms (✓)</li><li>Rule evaluation: &lt;50ms (✓)</li><li>Canvas sync: &lt;5 sec (✓)</li></ul><p>See <code>PERFORMANCE_BENCHMARK.md</code> for details.</p><h2 id="aspirational-coverage" tabindex="-1">Aspirational Coverage <a class="header-anchor" href="#aspirational-coverage" aria-label="Permalink to &quot;Aspirational Coverage&quot;">​</a></h2><p>Areas marked for v1.1+:</p><ul><li>Custom Lua expressions (rule engine)</li><li>Connector marketplace security audits</li><li>Coaching ML model validation</li><li>Cross-timezone DST handling</li><li>Large-scale event store optimization</li></ul><h2 id="tooling" tabindex="-1">Tooling <a class="header-anchor" href="#tooling" aria-label="Permalink to &quot;Tooling&quot;">​</a></h2><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Coverage report</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> tarpaulin</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --out</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> Html</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Coverage with detailed breakdown</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> tarpaulin</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --out</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> Report</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Critical path only</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> test</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --lib</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --test</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> integration</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --test-threads=1</span></span></code></pre></div><h2 id="last-updated" tabindex="-1">Last Updated <a class="header-anchor" href="#last-updated" aria-label="Permalink to &quot;Last Updated&quot;">​</a></h2><p>2026-04-23 (aligned with v0.0.1 scaffold)</p><p>See <a href="./../architecture/adrs">ADRs</a> for coverage philosophy.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("reference/honest-coverage.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const honestCoverage = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  honestCoverage as default
};
