import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Rituals","description":"Design daily and weekly ceremonies to anchor your screen-time habits.","frontmatter":{"title":"Rituals","description":"Design daily and weekly ceremonies to anchor your screen-time habits."},"headers":[],"relativePath":"rituals/index.md","filePath":"rituals/index.md","lastUpdated":1777002546000}');
const _sfc_main = { name: "rituals/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="rituals" tabindex="-1">Rituals <a class="header-anchor" href="#rituals" aria-label="Permalink to &quot;Rituals&quot;">​</a></h1><p><strong>Rituals</strong> are scheduled check-ins and ceremonies that help you reflect on your screen-time patterns and set intentions for the day ahead.</p><h2 id="core-rituals" tabindex="-1">Core Rituals <a class="header-anchor" href="#core-rituals" aria-label="Permalink to &quot;Core Rituals&quot;">​</a></h2><h3 id="morning-brief" tabindex="-1">Morning Brief <a class="header-anchor" href="#morning-brief" aria-label="Permalink to &quot;Morning Brief&quot;">​</a></h3><p>Every morning, FocalPoint presents a brief dashboard showing:</p><ul><li><strong>Sleep quality</strong> (from Apple Health integration)</li><li><strong>Today&#39;s calendar &amp; deadlines</strong> (Canvas, Google Calendar)</li><li><strong>Suggested focus sessions</strong> (based on schedule and past patterns)</li><li><strong>Streak status</strong> (days without distraction blocks)</li></ul><p>Estimated read time: <strong>2–3 minutes</strong></p><p>See <strong><a href="./morning-brief">Morning Brief Guide</a></strong> for customization options.</p><h3 id="evening-shutdown" tabindex="-1">Evening Shutdown <a class="header-anchor" href="#evening-shutdown" aria-label="Permalink to &quot;Evening Shutdown&quot;">​</a></h3><p>Before bed, FocalPoint prompts a 5-minute reflection:</p><ul><li><strong>Time audit</strong>: How much time did you spend on focused work vs. distraction?</li><li><strong>Goals reflection</strong>: Did you hit your study blocks or wellness targets?</li><li><strong>Tomorrow&#39;s intention</strong>: What&#39;s one priority for tomorrow?</li></ul><p>The shutdown is logged to your audit chain. Over time, patterns emerge.</p><p>See <strong><a href="./evening-shutdown">Evening Shutdown Guide</a></strong> for ritual design.</p><h2 id="custom-rituals" tabindex="-1">Custom Rituals <a class="header-anchor" href="#custom-rituals" aria-label="Permalink to &quot;Custom Rituals&quot;">​</a></h2><p>Advanced users can design their own ceremonies:</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">ritual</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Weekly Retrospective&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  schedule</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;every Sunday at 19:00&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  prompts</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;What went well this week?&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;What blocked my focus most?&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;What&#39;s one habit to improve?&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  actions</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">export_audit_chain</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;weekly-report.json&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">send_email</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;coaching@focalpoint.local&quot;</span></span></code></pre></div><h2 id="ritual-architecture" tabindex="-1">Ritual Architecture <a class="header-anchor" href="#ritual-architecture" aria-label="Permalink to &quot;Ritual Architecture&quot;">​</a></h2><p>Rituals are:</p><ul><li><strong>Time-triggered</strong> via the system scheduler (cron-like rules)</li><li><strong>Logged</strong> to the audit chain for transparency</li><li><strong>Customizable</strong> by users (frequency, prompts, actions)</li><li><strong>Privacy-respecting</strong> (exported data stays local unless user opts to share)</li></ul><p>Rituals empower reflection without being invasive.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("rituals/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
