import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Morning Brief Ritual","description":"Start your day with intention—see your schedule, sleep quality, and focus goals.","frontmatter":{"title":"Morning Brief Ritual","description":"Start your day with intention—see your schedule, sleep quality, and focus goals."},"headers":[],"relativePath":"rituals/morning-brief.md","filePath":"rituals/morning-brief.md","lastUpdated":1777002546000}');
const _sfc_main = { name: "rituals/morning-brief.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="morning-brief-ritual" tabindex="-1">Morning Brief Ritual <a class="header-anchor" href="#morning-brief-ritual" aria-label="Permalink to &quot;Morning Brief Ritual&quot;">​</a></h1><p>The <strong>Morning Brief</strong> is a 2–3 minute daily ceremony that starts your day with intention.</p><h2 id="what-you-see" tabindex="-1">What You See <a class="header-anchor" href="#what-you-see" aria-label="Permalink to &quot;What You See&quot;">​</a></h2><h3 id="_1-sleep-quality-from-apple-health" tabindex="-1">1. Sleep Quality (from Apple Health) <a class="header-anchor" href="#_1-sleep-quality-from-apple-health" aria-label="Permalink to &quot;1. Sleep Quality (from Apple Health)&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>😴 Sleep: 7h 15m (Good)</span></span>
<span class="line"><span>   Debt: -30 min (recovering!)</span></span></code></pre></div><p>Shows sleep duration and how you&#39;re tracking against your sleep goal.</p><h3 id="_2-today-s-calendar-deadlines" tabindex="-1">2. Today&#39;s Calendar &amp; Deadlines <a class="header-anchor" href="#_2-today-s-calendar-deadlines" aria-label="Permalink to &quot;2. Today&#39;s Calendar &amp; Deadlines&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>📅 Schedule:</span></span>
<span class="line"><span>   • 9:00 AM – CS 101 Lecture</span></span>
<span class="line"><span>   • 2:00 PM – Project deadline (Canvas)</span></span>
<span class="line"><span>   • 4:30 PM – Team standup</span></span></code></pre></div><p>Automatically pulls from Google Calendar and Canvas.</p><h3 id="_3-suggested-focus-sessions" tabindex="-1">3. Suggested Focus Sessions <a class="header-anchor" href="#_3-suggested-focus-sessions" aria-label="Permalink to &quot;3. Suggested Focus Sessions&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>🎯 Focus opportunities:</span></span>
<span class="line"><span>   1. Before 9 AM – Review lecture slides (30 min)</span></span>
<span class="line"><span>   2. 10 AM – Start project work (90 min)</span></span>
<span class="line"><span>   3. Lunch break – Recharge (45 min)</span></span></code></pre></div><p>Based on your calendar + assignments + past focus patterns.</p><h3 id="_4-streak-status" tabindex="-1">4. Streak Status <a class="header-anchor" href="#_4-streak-status" aria-label="Permalink to &quot;4. Streak Status&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>🔥 Current streaks:</span></span>
<span class="line"><span>   • 7-day focus streak (great!)</span></span>
<span class="line"><span>   • 3-day early submission streak</span></span></code></pre></div><p>Celebrate momentum and inspire consistency.</p><h2 id="customization" tabindex="-1">Customization <a class="header-anchor" href="#customization" aria-label="Permalink to &quot;Customization&quot;">​</a></h2><h3 id="timing" tabindex="-1">Timing <a class="header-anchor" href="#timing" aria-label="Permalink to &quot;Timing&quot;">​</a></h3><ul><li><strong>Default</strong>: 6:30 AM (configurable)</li><li><strong>Weekday-only</strong>: Skip weekends</li><li><strong>Adaptive</strong>: Move based on first calendar event</li></ul><h3 id="content" tabindex="-1">Content <a class="header-anchor" href="#content" aria-label="Permalink to &quot;Content&quot;">​</a></h3><p>Disable/enable specific sections:</p><ul><li>Sleep quality (requires Apple Health)</li><li>Calendar sync</li><li>Focus suggestions</li><li>Streak display</li></ul><h3 id="presentation" tabindex="-1">Presentation <a class="header-anchor" href="#presentation" aria-label="Permalink to &quot;Presentation&quot;">​</a></h3><ul><li><strong>Text-only</strong>: Plain summary</li><li><strong>Cards</strong>: Visual layout (default)</li><li><strong>Voice</strong>: Audio brief (via Siri, if enabled)</li></ul><h2 id="ritual-flow" tabindex="-1">Ritual Flow <a class="header-anchor" href="#ritual-flow" aria-label="Permalink to &quot;Ritual Flow&quot;">​</a></h2><ol><li><strong>Wakeup</strong>: Brief appears in notification or app</li><li><strong>Review</strong>: Read key info (30 seconds)</li><li><strong>Select</strong>: Pick a focus goal or task (1 minute)</li><li><strong>Commit</strong>: Start a focus session or review your calendar (1 minute)</li><li><strong>Dismiss</strong>: Brief exits; you start your day</li></ol><h2 id="example-student-morning" tabindex="-1">Example: Student Morning <a class="header-anchor" href="#example-student-morning" aria-label="Permalink to &quot;Example: Student Morning&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>6:30 AM: Morning Brief appears</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Sleep: 6h 45m (slight debt)</span></span>
<span class="line"><span>Today:</span></span>
<span class="line"><span>  • 9 AM – CS 101</span></span>
<span class="line"><span>  • 2 PM – Midterm project due ⚠️</span></span>
<span class="line"><span>  • 4 PM – Office hours</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Focus suggestions:</span></span>
<span class="line"><span>  1. 7–8 AM: Review lecture notes (30 min)</span></span>
<span class="line"><span>  2. 9 AM–12 PM: Midterm work sprint (180 min)</span></span>
<span class="line"><span>  3. 1 PM: Lunch break (45 min)</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Streaks: 5 days (keep going!)</span></span>
<span class="line"><span></span></span>
<span class="line"><span>👉 &quot;Start focus session?&quot;</span></span>
<span class="line"><span>   [Yes] [Maybe later] [Dismiss]</span></span></code></pre></div><h2 id="integration-with-rules" tabindex="-1">Integration with Rules <a class="header-anchor" href="#integration-with-rules" aria-label="Permalink to &quot;Integration with Rules&quot;">​</a></h2><p>The Morning Brief can trigger rules:</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">trigger</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">schedule</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;every morning at 06:30&quot;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">show_morning_brief</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">coach_message</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Let&#39;s make today great!&quot;</span></span></code></pre></div><h2 id="privacy" tabindex="-1">Privacy <a class="header-anchor" href="#privacy" aria-label="Permalink to &quot;Privacy&quot;">​</a></h2><ul><li>All data is local (Apple Health, Calendar stored on device)</li><li>No cloud sync by default</li><li>Users can disable specific sources</li><li>Audit log tracks when brief was viewed</li></ul><h2 id="ritual-archetype-productivity-kickoff" tabindex="-1">Ritual Archetype: Productivity Kickoff <a class="header-anchor" href="#ritual-archetype-productivity-kickoff" aria-label="Permalink to &quot;Ritual Archetype: Productivity Kickoff&quot;">​</a></h2><p>For general productivity:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Schedule + Focus opportunities + Streak status</span></span>
<span class="line"><span>(No sleep data unless you have Apple Health enabled)</span></span></code></pre></div><h2 id="ritual-archetype-sleep-wellness" tabindex="-1">Ritual Archetype: Sleep Wellness <a class="header-anchor" href="#ritual-archetype-sleep-wellness" aria-label="Permalink to &quot;Ritual Archetype: Sleep Wellness&quot;">​</a></h2><p>For sleep-focused users:</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Sleep debt + Suggested recovery time + Energy levels</span></span>
<span class="line"><span>(No calendar unless busy day detected)</span></span></code></pre></div><h2 id="schedule-configuration" tabindex="-1">Schedule Configuration <a class="header-anchor" href="#schedule-configuration" aria-label="Permalink to &quot;Schedule Configuration&quot;">​</a></h2><p>Ritual runs at configured time via system scheduler. No cloud dependency.</p><p>See <strong><a href="./index">Rituals Overview</a></strong> for how to create custom rituals.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("rituals/morning-brief.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const morningBrief = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  morningBrief as default
};
