import Foundation

/// Placeholder namespace for UniFFI-generated bindings from `crates/focus-ffi`.
///
/// Real Swift bindings will be generated by UniFFI and populate this module.
/// Until then, we expose a small surface that mirrors the Rust domain shapes
/// the UI layer needs, so Swift views can compile against stable types.
public enum FocalPointCore {
    public static let version = "0.0.1-placeholder"
}

/// Mirrors `focus_domain::RuleId` (opaque identifier).
public struct RuleId: Hashable, Codable, Sendable {
    public let raw: String
    public init(_ raw: String) { self.raw = raw }
}

/// Minimal placeholder for an active rule; the Rust side owns the real schema.
public struct ActiveRule: Hashable, Codable, Sendable {
    public let id: RuleId
    public let title: String
    public let endsAt: Date?

    public init(id: RuleId, title: String, endsAt: Date?) {
        self.id = id
        self.title = title
        self.endsAt = endsAt
    }
}
