// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(focus_ffiFFI)
import focus_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_focus_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_focus_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol FocalPointCoreProtocol : AnyObject {
    
    func appVersion()  -> String
    
    func mascotState()  -> MascotState
    
    func pushMascotEvent(event: MascotEvent)  -> MascotState
    
}

open class FocalPointCore:
    FocalPointCoreProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_focus_ffi_fn_clone_focalpointcore(self.pointer, $0) }
    }
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_focus_ffi_fn_constructor_focalpointcore_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_focus_ffi_fn_free_focalpointcore(pointer, $0) }
    }

    

    
open func appVersion() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_focus_ffi_fn_method_focalpointcore_app_version(self.uniffiClonePointer(),$0
    )
})
}
    
open func mascotState() -> MascotState {
    return try!  FfiConverterTypeMascotState.lift(try! rustCall() {
    uniffi_focus_ffi_fn_method_focalpointcore_mascot_state(self.uniffiClonePointer(),$0
    )
})
}
    
open func pushMascotEvent(event: MascotEvent) -> MascotState {
    return try!  FfiConverterTypeMascotState.lift(try! rustCall() {
    uniffi_focus_ffi_fn_method_focalpointcore_push_mascot_event(self.uniffiClonePointer(),
        FfiConverterTypeMascotEvent.lower(event),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFocalPointCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FocalPointCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FocalPointCore {
        return FocalPointCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FocalPointCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FocalPointCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FocalPointCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFocalPointCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> FocalPointCore {
    return try FfiConverterTypeFocalPointCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFocalPointCore_lower(_ value: FocalPointCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFocalPointCore.lower(value)
}


public struct MascotState {
    public var pose: Pose
    public var emotion: Emotion
    public var sinceIso: String
    public var bubbleText: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pose: Pose, emotion: Emotion, sinceIso: String, bubbleText: String?) {
        self.pose = pose
        self.emotion = emotion
        self.sinceIso = sinceIso
        self.bubbleText = bubbleText
    }
}



extension MascotState: Equatable, Hashable {
    public static func ==(lhs: MascotState, rhs: MascotState) -> Bool {
        if lhs.pose != rhs.pose {
            return false
        }
        if lhs.emotion != rhs.emotion {
            return false
        }
        if lhs.sinceIso != rhs.sinceIso {
            return false
        }
        if lhs.bubbleText != rhs.bubbleText {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pose)
        hasher.combine(emotion)
        hasher.combine(sinceIso)
        hasher.combine(bubbleText)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMascotState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MascotState {
        return
            try MascotState(
                pose: FfiConverterTypePose.read(from: &buf), 
                emotion: FfiConverterTypeEmotion.read(from: &buf), 
                sinceIso: FfiConverterString.read(from: &buf), 
                bubbleText: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: MascotState, into buf: inout [UInt8]) {
        FfiConverterTypePose.write(value.pose, into: &buf)
        FfiConverterTypeEmotion.write(value.emotion, into: &buf)
        FfiConverterString.write(value.sinceIso, into: &buf)
        FfiConverterOptionString.write(value.bubbleText, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMascotState_lift(_ buf: RustBuffer) throws -> MascotState {
    return try FfiConverterTypeMascotState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMascotState_lower(_ value: MascotState) -> RustBuffer {
    return FfiConverterTypeMascotState.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Emotion {
    
    case neutral
    case happy
    case proud
    case concerned
    case stern
    case excited
    case tired
    case warm
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEmotion: FfiConverterRustBuffer {
    typealias SwiftType = Emotion

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Emotion {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .neutral
        
        case 2: return .happy
        
        case 3: return .proud
        
        case 4: return .concerned
        
        case 5: return .stern
        
        case 6: return .excited
        
        case 7: return .tired
        
        case 8: return .warm
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Emotion, into buf: inout [UInt8]) {
        switch value {
        
        
        case .neutral:
            writeInt(&buf, Int32(1))
        
        
        case .happy:
            writeInt(&buf, Int32(2))
        
        
        case .proud:
            writeInt(&buf, Int32(3))
        
        
        case .concerned:
            writeInt(&buf, Int32(4))
        
        
        case .stern:
            writeInt(&buf, Int32(5))
        
        
        case .excited:
            writeInt(&buf, Int32(6))
        
        
        case .tired:
            writeInt(&buf, Int32(7))
        
        
        case .warm:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEmotion_lift(_ buf: RustBuffer) throws -> Emotion {
    return try FfiConverterTypeEmotion.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEmotion_lower(_ value: Emotion) -> RustBuffer {
    return FfiConverterTypeEmotion.lower(value)
}



extension Emotion: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MascotEvent {
    
    case ruleFired(ruleName: String
    )
    case streakIncremented(name: String, count: UInt32
    )
    case streakReset(name: String
    )
    case creditEarned(amount: Int64
    )
    case bypassSpent(remaining: Int64
    )
    case penaltyEscalated(tier: String
    )
    case appLaunchedWhileBlocked(bundleId: String
    )
    case focusSessionStarted(minutes: UInt32
    )
    case focusSessionCompleted(minutes: UInt32
    )
    case dailyCheckIn
    case sleepDebtReported(hours: Float
    )
    case idle
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMascotEvent: FfiConverterRustBuffer {
    typealias SwiftType = MascotEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MascotEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .ruleFired(ruleName: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .streakIncremented(name: try FfiConverterString.read(from: &buf), count: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 3: return .streakReset(name: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .creditEarned(amount: try FfiConverterInt64.read(from: &buf)
        )
        
        case 5: return .bypassSpent(remaining: try FfiConverterInt64.read(from: &buf)
        )
        
        case 6: return .penaltyEscalated(tier: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .appLaunchedWhileBlocked(bundleId: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .focusSessionStarted(minutes: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 9: return .focusSessionCompleted(minutes: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 10: return .dailyCheckIn
        
        case 11: return .sleepDebtReported(hours: try FfiConverterFloat.read(from: &buf)
        )
        
        case 12: return .idle
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MascotEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .ruleFired(ruleName):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(ruleName, into: &buf)
            
        
        case let .streakIncremented(name,count):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(name, into: &buf)
            FfiConverterUInt32.write(count, into: &buf)
            
        
        case let .streakReset(name):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(name, into: &buf)
            
        
        case let .creditEarned(amount):
            writeInt(&buf, Int32(4))
            FfiConverterInt64.write(amount, into: &buf)
            
        
        case let .bypassSpent(remaining):
            writeInt(&buf, Int32(5))
            FfiConverterInt64.write(remaining, into: &buf)
            
        
        case let .penaltyEscalated(tier):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(tier, into: &buf)
            
        
        case let .appLaunchedWhileBlocked(bundleId):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(bundleId, into: &buf)
            
        
        case let .focusSessionStarted(minutes):
            writeInt(&buf, Int32(8))
            FfiConverterUInt32.write(minutes, into: &buf)
            
        
        case let .focusSessionCompleted(minutes):
            writeInt(&buf, Int32(9))
            FfiConverterUInt32.write(minutes, into: &buf)
            
        
        case .dailyCheckIn:
            writeInt(&buf, Int32(10))
        
        
        case let .sleepDebtReported(hours):
            writeInt(&buf, Int32(11))
            FfiConverterFloat.write(hours, into: &buf)
            
        
        case .idle:
            writeInt(&buf, Int32(12))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMascotEvent_lift(_ buf: RustBuffer) throws -> MascotEvent {
    return try FfiConverterTypeMascotEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMascotEvent_lower(_ value: MascotEvent) -> RustBuffer {
    return FfiConverterTypeMascotEvent.lower(value)
}



extension MascotEvent: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Pose {
    
    case confident
    case encouraging
    case curiousThinking
    case sternToughLove
    case celebratory
    case sleepyDisappointed
    case idle
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePose: FfiConverterRustBuffer {
    typealias SwiftType = Pose

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Pose {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .confident
        
        case 2: return .encouraging
        
        case 3: return .curiousThinking
        
        case 4: return .sternToughLove
        
        case 5: return .celebratory
        
        case 6: return .sleepyDisappointed
        
        case 7: return .idle
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Pose, into buf: inout [UInt8]) {
        switch value {
        
        
        case .confident:
            writeInt(&buf, Int32(1))
        
        
        case .encouraging:
            writeInt(&buf, Int32(2))
        
        
        case .curiousThinking:
            writeInt(&buf, Int32(3))
        
        
        case .sternToughLove:
            writeInt(&buf, Int32(4))
        
        
        case .celebratory:
            writeInt(&buf, Int32(5))
        
        
        case .sleepyDisappointed:
            writeInt(&buf, Int32(6))
        
        
        case .idle:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePose_lift(_ buf: RustBuffer) throws -> Pose {
    return try FfiConverterTypePose.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePose_lower(_ value: Pose) -> RustBuffer {
    return FfiConverterTypePose.lower(value)
}



extension Pose: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_focus_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_focus_ffi_checksum_method_focalpointcore_app_version() != 17901) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_focus_ffi_checksum_method_focalpointcore_mascot_state() != 37207) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_focus_ffi_checksum_method_focalpointcore_push_mascot_event() != 5154) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_focus_ffi_checksum_constructor_focalpointcore_new() != 24212) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all